# Generated by Django 3.2.5 on 2022-04-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('photo', models.FileField(upload_to='static/image/')),
            ],
            options={
                'db_table': 'u_photo',
            },
        ),
        migrations.CreateModel(
            name='Inquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('contents', models.TextField(blank=True, verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('answer', models.TextField(null=True, verbose_name='답변')),
                ('answer_date', models.DateTimeField(auto_now=True, verbose_name='답변일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변(들)',
                'db_table': 't_inquire',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, verbose_name='게시글 종류')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('e_start', models.DateField(null=True, verbose_name='이벤트 시작일')),
                ('e_end', models.DateField(null=True, verbose_name='이벤트 종료일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글(들)',
                'db_table': 't_board',
            },
        ),
        migrations.CreateModel(
            name='B_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=300, null=True, verbose_name='게시물이미지')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs.board')),
            ],
            options={
                'verbose_name': '게시물사진',
                'verbose_name_plural': '게시물사진(들)',
                'db_table': 'b_photo',
            },
        ),
    ]
