# Generated by Django 3.2.5 on 2022-04-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_account',
            fields=[
                ('bank', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='은행명')),
                ('number', models.CharField(max_length=60, verbose_name='계좌번호')),
                ('depositer', models.CharField(max_length=30, verbose_name='예금주')),
            ],
            options={
                'verbose_name': '회사계좌',
                'verbose_name_plural': '회사계좌(들)',
                'db_table': 't_co_account',
            },
        ),
    ]
