# Generated by Django 3.2.5 on 2022-04-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='크기')),
                ('request', models.CharField(max_length=200, null=True, verbose_name='요청사항')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='상품등록일')),
                ('img', models.CharField(max_length=300, verbose_name='이미지')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품(들)',
                'db_table': 't_product',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='타입명')),
                ('description', models.CharField(max_length=5000, verbose_name='타입설명')),
                ('img', models.CharField(max_length=5000, verbose_name='이미지')),
                ('price', models.IntegerField(default=0, verbose_name='타입가격')),
            ],
            options={
                'verbose_name': '타입',
                'verbose_name_plural': '타입(들)',
                'db_table': 't_type',
            },
        ),
        migrations.CreateModel(
            name='Tag_list',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='태그이름')),
                ('product', models.ManyToManyField(to='recommendation.Product', verbose_name='물품')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그(들)',
                'db_table': 't_tag_list',
            },
        ),
        migrations.CreateModel(
            name='T_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=300, verbose_name='타입이미지')),
                ('color', models.CharField(max_length=300, verbose_name='타입색')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.type', verbose_name='타입명')),
            ],
            options={
                'verbose_name': '타입사진',
                'verbose_name_plural': '타입사진(들)',
                'db_table': 't_photo',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.type', verbose_name='타입명'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자'),
        ),
        migrations.CreateModel(
            name='P_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=300, verbose_name='완성품이미지')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '완성품사진',
                'verbose_name_plural': '완성품사진(들)',
                'db_table': 'p_photo',
            },
        ),
    ]
