# Generated by Django 3.2.5 on 2022-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False, verbose_name='관리자모드')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='닉네임')),
                ('contact', models.CharField(max_length=30, verbose_name='연락처')),
                ('point', models.IntegerField(default=0, verbose_name='적립금')),
                ('adress', models.CharField(default='____', max_length=300, verbose_name='주소')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원(들)',
                'db_table': 't_user',
            },
        ),
    ]
