# Generated by Django 3.2.5 on 2022-04-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prized',
            field=models.BooleanField(default=False, verbose_name='베스트상 수상'),
        ),
    ]
