# Generated by Django 3.2.5 on 2022-04-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='상품갯수')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
                ('state', models.CharField(max_length=10, verbose_name='상태')),
                ('delivery_req', models.CharField(max_length=100, verbose_name='배송요청사항')),
                ('r_name', models.CharField(max_length=80, verbose_name='받는분이름')),
                ('r_adress', models.CharField(max_length=300, verbose_name='받는분주소')),
                ('r_contact', models.CharField(max_length=300, verbose_name='연락처')),
                ('r_location', models.CharField(max_length=80, verbose_name='배송위치')),
                ('r_pw', models.IntegerField(default=0, verbose_name='공동현관비밀번호')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.product', verbose_name='상품번호')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='구매자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문(들)',
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='Review_photo_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('photo', models.FileField(upload_to='static/image/product_review/')),
            ],
            options={
                'db_table': 'u_photos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='후기제목')),
                ('contents', models.CharField(max_length=300, verbose_name='후기내용')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='후기조회수')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='주문번호')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰(들)',
                'db_table': 't_review',
            },
        ),
        migrations.CreateModel(
            name='R_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=300, verbose_name='사진')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.review', verbose_name='주문번호')),
            ],
            options={
                'verbose_name': '리뷰사진',
                'verbose_name_plural': '리뷰사진(들)',
                'db_table': 'r_photo',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=True, verbose_name='체크여부')),
                ('amount', models.IntegerField(default=1, verbose_name='갯수')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.product', verbose_name='완성품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='디자이너')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니(들)',
                'db_table': 't_cart',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
